image: bemyak/godot-ci:3.2.3

variables:
  EXPORT_NAME: game_name

stages:
  - export
  - deploy

linux:
  stage: export
  script:
    - mkdir -v -p build/linux
    - godot -v --export "Linux/X11" ./build/linux/${EXPORT_NAME}.x86_64
  artifacts:
    name: ${EXPORT_NAME}-${CI_JOB_NAME}
    paths:
      - build/linux

windows:
  stage: export
  script:
    - mkdir -v -p build/windows
    - godot -v --export "Windows Desktop" ./build/windows/${EXPORT_NAME}.exe
  artifacts:
    name: ${EXPORT_NAME}-${CI_JOB_NAME}
    paths:
      - build/windows

mac:
  stage: export
  script:
    - mkdir -v -p build/mac
    - godot -v --export "Mac OSX" ./build/mac/${EXPORT_NAME}.zip
  artifacts:
    name: ${EXPORT_NAME}-${CI_JOB_NAME}
    paths:
      - build/mac

web:
  stage: export
  script:
    - mkdir -v -p build/web
    - godot -v --export "HTML5" ./build/web/index.html
  artifacts:
    name: ${EXPORT_NAME}-${CI_JOB_NAME}
    paths:
      - build/web

android:
  stage: export
  script:
    - mkdir -v -p build/android
    - godot -v --export "Android" ./build/android/${EXPORT_NAME}.apk
  artifacts:
    name: ${EXPORT_NAME}-${CI_JOB_NAME}
    paths:
      - build/android

# Use project root to deploy for the gh-pages branch
deploy-github-pages:
  stage: deploy
  dependencies:
    - web
  script:
    - git checkout gh-pages
    - rm -f *.md
    - mv build/web/** .
    - git config user.email $GIT_EMAIL
    - git config user.name $GIT_USERNAME
    - git remote add github $REMOTE_URL
    - git add -A
    - 'git commit -m "ci: Deploy GitHub Page ${EXPORT_NAME}-${CI_JOB_NAME}$" -m "Deploy from GitLab pipeline \#${CI_PIPELINE_ID}"'
    - git push github gh-pages -f
